### ISSUE TITLE
use h2o::with_no_h2o_progress

### ISSUE THREAD

**Issue by topepo** [tidymodels/agua#13]
In the very latest h2o version, they have this function documented ~exported~. This should stop the progress bars and some other output. 

edit: @ledell @tomasfryda Was the function supposed to be exported (since it is documented)?

**Comment by ledell** [comment]
@topepo This is working now (we modified it so that you can wrap the `h2o.no_progress()` and `h2o.show_progress()` around any H2O function to turn on/off progress bars.  Available on the nightly releases from master: https://h2o-release.s3.amazonaws.com/h2o/master/latest.html

**Comment by qiushiyan** [comment]
@ledell Could we expect a new cran version any time soon?

**Comment by ledell** [comment]
@qiushiyan The current ETA is early August.
