### ISSUE TITLE
Error segfault

### ISSUE THREAD

**Issue by gouthaman87** [tidymodels/agua#40]
Getting following error when fitting drf model
Warning: stack imbalance in 'as.environment', 249 then 246
 *** caught segfault ***
 *** caught segfault ***
 *** caught segfault ***
address 0x64209498, cause 'memory not mapped'
 *** caught segfault ***
 *** caught segfault ***
address 0x64209498, cause 'memory not mapped'
 *** caught segfault ***
address 0x64209498, cause 'memory not mapped'
address 0x7fcfd18a4e7a, cause 'invalid permissions'
 *** caught segfault ***
address 0x64209498, cause 'memory not mapped'

**Comment by qiushiyan** [comment]
Can you provide a [reprex](https://reprex.tidyverse.org/)?

**Comment by qiushiyan** [comment]
Closed due to the lack of examples.
