### ISSUE TITLE
Use of set_dependency() should use `mode` argument

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/agua#51]
Original bug found in https://github.com/tidymodels/censored/pull/269.

It isn't that much work for us to specify it and it stops us from being bitten later down the line.

**Comment by qiushiyan** [comment]
The model definitions are cleaned up in https://github.com/tidymodels/agua/commit/dfc7a13ad37d5ddbe58cb4d37f6b4de494118a20
